name: Run Script

on:
  push:
    branches: [ "main" ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run my JS script
        env:
          BACKEND_APP_PK: ${{ secrets.BACKEND_APP_PK }}
          CLIENTID: ${{ vars.CLIENTID }}
          AUDIENCEURL: ${{ vars.AUDIENCEURL }}
        run: node js/backend-app.js
